### ISSUE TITLE
Error, not work on laptop win 10

### ISSUE THREAD

**Issue by thucngocle85** [Olney1/ChatGPT-OpenAI-Smart-Speaker#2]
D:\New folder\ChatGPT-OpenAI-Smart-Speaker-main>python smart_speaker.py
Say something!
result2:
{   'alternative': [   {   'confidence': 0.79627585,
                           'transcript': 'same time captain'},
                       {'transcript': 'same time come on'},
                       {'transcript': 'same time'},
                       {'transcript': 'same time okay'},
                       {'transcript': 'same time cap on'}],
    'final': True}
Google Speech Recognition thinks you said same time captain
result2:
{   'alternative': [   {   'confidence': 0.79627585,
                           'transcript': 'same time captain'},
                       {'transcript': 'same time come on'},
                       {'transcript': 'same time'},
                       {'transcript': 'same time okay'},
                       {'transcript': 'same time cap on'}],
    'final': True}
This is the prompt being sent to OpenAIsame time captain
 james cook was born in marton-in-cleveland, england

1728
'mpg321' is not recognized as an internal or external command,
operable program or batch file.

    Error 263 for command:
        open response.mp3
    The specified device is not open or is not recognized by MCI.

    Error 263 for command:
        close response.mp3
    The specified device is not open or is not recognized by MCI.
Failed to close the file: response.mp3
Traceback (most recent call last):
  File "D:\New folder\ChatGPT-OpenAI-Smart-Speaker-main\smart_speaker.py", line 68, in <module>
    main()
  File "D:\New folder\ChatGPT-OpenAI-Smart-Speaker-main\smart_speaker.py", line 65, in main
    play_audio_file()
  File "D:\New folder\ChatGPT-OpenAI-Smart-Speaker-main\smart_speaker.py", line 55, in play_audio_file
    playsound("response.mp3", block=False) # There’s an optional second argument, block, which is set to True by default. Setting it to False makes the function run asynchronously.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\thucn\AppData\Local\Programs\Python\Python311\Lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "C:\Users\thucn\AppData\Local\Programs\Python\Python311\Lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open response.mp3
    The specified device is not open or is not recognized by MCI.

**Comment by Olney1** [comment]
The error message "mpg321 is not recognized as an internal or external command" suggests that the script is trying to play an audio file using the mpg321 command, but it is not installed or accessible on your system. You may need to install this command or modify the script to use a different audio player.

The error message "Error 263 for command: open response.mp3" suggests that the script is failing to open the response audio file. This could be due to a problem with the file path or permissions. You may need to check that the file exists and is accessible, and that you have the appropriate permissions to access it.

The error message "The specified device is not open or is not recognized by MCI" suggests that there may be an issue with the audio device being used by your system. You may need to check that your speakers or headphones are connected and working properly, and that your system is configured to use the correct audio device.
